#!/bin/sh

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='(Compiled by WMD)'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt '" >> /etc/openwrt_release
sed -i '/DISTRIB_LASTMODIFIELD/d' /etc/openwrt_release
echo "DISTRIB_LASTMODIFIELD='$(date "+%Y-%m-%d %H:%M:%S")'" >> /etc/openwrt_release
# Replace Hostname
sed -i "s/hostname .*/hostname 'WMD-Router'/" /etc/config/system
# change password for root
sed -i 's/root:.*/root:$1$10.eH9sr$MLGIXwXEg4kusnnjUDHmO0:19172:0:99999:7:::/g' /etc/shadow
exit 0
