#!/bin/sh
# set system Hostname/timezone/zonename
uci -q batch <<-EOF
	set system.@system[0].hostname='gssiRouter'
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'

	delete system.ntp.server
	add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp1.aliyun.com'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='cn.ntp.org.cn'
EOF
uci commit system

# set network lan...
uci -q batch <<-EOF
	uci set network.lan.proto='static'
	uci set network.lan.device='br-lan'
	uci set network.lan.ipaddr='10.10.10.254'
	uci set network.lan.netmask='255.255.255.0'
	uci set network.lan.broadcast='10.10.10.255'
	uci set network.lan.dns='223.5.5.5 223.6.6.6'
EOF
uci commit network

# Set file /etc/openwrt_release
sed -i '/DISTRIB_ID/d' /etc/openwrt_release
echo "DISTRIB_ID='gssiRouter '" >> /etc/openwrt_release
sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='$(date "+%Y-%m-%d")'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='gssiRouter '" >> /etc/openwrt_release
sed -i '/DISTRIB_LASTMODIFIELD/d' /etc/openwrt_release
echo "DISTRIB_LASTMODIFIELD='Compiled by Wangmingde $(date "+%Y-%m-%d %H:%M:%S")'" >> /etc/openwrt_release

# Set Default password of root
sed -i 's/root:.*/root:$1$Ds8BJ34B$Lm19IlaiTFvnFFLYDvEU6.:19172:0:99999:7:::/' /etc/shadow

# Set banner
mv /etc/gssiwmd_banner /etc/banner

# Set sysinfo.sh
mv /etc/gssiwmd_sysinfo.sh /etc/profile.d/sysinfo.sh

exit 0
